EXPECTED_SERVICES = ()

EXPECTED_SERVICE_TYPES = (
    'Jobs and workplace',
    'Claims or benefits',
    'I am getting divorced',
)

EXPECTED_LIFE_EVENTS = (
    'I am employing someone for the first time',
    'I have lost my job',
    'I am leaving school and wondering what next',
    'Closing a business',
    'Starting a business',
)

EXPECTED_SUBSERVICES = (
    {"id": "CMP_035", "agency": "QWERTY", "name": "Accommodation Details"},
    {"id": "CMP_098", "agency": "QWERTY", "name": "Accommodation"},
    {"id": "CMP_199", "agency": "QWERTY", "name": "Activity Test"},
    {"id": "CMP_200", "agency": "QWERTY", "name": "Activity Test Exemption"},
    {"id": "CMP_225", "agency": "QWERTY", "name": "Activity Test Review"},
    {"id": "CMP_163", "agency": "QWERTY", "name": "Additional Entitlements "},
    {"id": "CMP_099", "agency": "QWERTY", "name": "Address"},
    {"id": "CMP_277", "agency": "QWERTY", "name": "Administrative Appeals Tribunal (AAT)"},
    {"id": "CMP_150", "agency": "QWERTY", "name": "Administrative Compensation"},
    {"id": "CMP_144", "agency": "QWERTY", "name": "Advance Payment (FTB / MOB / Generic)"},
    {"id": "CMP_194", "agency": "QWERTY", "name": "AMEP"},
    {"id": "CMP_226", "agency": "QWERTY", "name": "AOS Reviews"},
    {"id": "CMP_037", "agency": "QWERTY", "name": "Assurance of Support"},
    {"id": "CMP_145", "agency": "QWERTY", "name": "Assurance of Support (Release of Bank Guarantee)"},
    {"id": "CMP_253", "agency": "QWERTY", "name": "Australia Post Commission"},
    {"id": "CMP_278", "agency": "QWERTY", "name": "Authorised Review Officer (ARO)"},
    {"id": "CMP_173", "agency": "QWERTY", "name": "Basics Card",},
    {"id": "CMP_019", "agency": "QWERTY", "name": "Book Appointment",},
    {"id": "CMP_100", "agency": "QWERTY", "name": "Business Details",},
    {"id": "CMP_146", "agency": "QWERTY", "name": "Cancellation of Entitlement",},
    {"id": "CMP_148", "agency": "QWERTY", "name": "Centrepay",},
    {"id": "CMP_107", "agency": "QWERTY", "name": "Change Customer Details"},
    {"id": "CMP_149", "agency": "QWERTY", "name": "Child Support Agency Deductions"},
    {"id": "CMP_254", "agency": "QWERTY", "name": "Collector of Public Monies"},
    {"id": "CMP_006", "agency": "QWERTY", "name": "Claim Lodgement"},
    {"id": "CMP_007", "agency": "QWERTY", "name": "Coding / Verification of Customers Generic Details",},
    {"id": "CMP_042", "agency": "QWERTY", "name": "Compensation Assessment"},
    {"id": "CMP_255", "agency": "QWERTY", "name": "Compensation Recovery"},
    {"id": "CMP_229", "agency": "QWERTY", "name": "Compliance Reviews"},
    {"id": "CMP_222", "agency": "QWERTY", "name": "Comprehensive Compliance Assessment"},
    {"id": "CMP_187", "agency": "QWERTY", "name": "Concession Card Re-issue"},
    {"id": "CMP_020", "agency": "QWERTY", "name": "Conduct Interview"},
    {"id": "CMP_008", "agency": "QWERTY", "name": "Create Customer Record"},
    {"id": "CMP_256", "agency": "QWERTY", "name": "Debt Raising"},
    {"id": "CMP_257", "agency": "QWERTY", "name": "Debt Recovery"},
    {"id": "CMP_258", "agency": "QWERTY", "name": "Debt Repayments"},
    {"id": "CMP_103", "agency": "QWERTY", "name": "Deceased Customer"},
    {"id": "CMP_026", "agency": "QWERTY", "name": "Deny Access Facility"},
    {"id": "CMP_230", "agency": "QWERTY", "name": "Department of Corrective Services Reviews"},
    {"id": "CMP_269", "agency": "QWERTY", "name": "Departure Prohibition Order"},
    {"id": "CMP_231", "agency": "QWERTY", "name": "DHA Reviews"},
    {"id": "CMP_232", "agency": "QWERTY", "name": "DIBP Reviews"},
    {"id": "CMP_286", "agency": "QWERTY", "name": "Duplicate Form Issue"},
    {"id": "CMP_129", "agency": "QWERTY", "name": "DVA Updates"},
    {"id": "CMP_287", "agency": "QWERTY", "name": "Early Release of Superannuation (Hardship Assessment)"},
    {"id": "CMP_010", "agency": "QWERTY", "name": "Electronic Messaging"},
    {"id": "CMP_002", "agency": "QWERTY", "name": "Eligibility Entitlement Discussion"},
    {"id": "CMP_201", "agency": "QWERTY", "name": "Employer Contact Certificates"},
    {"id": "CMP_044", "agency": "QWERTY", "name": "Employment  Details / Earnings                "},
    {"id": "CMP_202", "agency": "QWERTY", "name": "Employment Pathway / Participation Plan",},
    {"id": "CMP_203", "agency": "QWERTY", "name": "Employment Pathway / Participation Plan Review"},
    {"id": "CMP_223", "agency": "QWERTY", "name": "Employment Services Assessment (ESAt)"},
    {"id": "CMP_195", "agency": "QWERTY", "name": "Employment Services Provider Referral / Connection"},
    {"id": "CMP_204", "agency": "QWERTY", "name": "Employment Services Provider Registration"},
    {"id": "CMP_025", "agency": "QWERTY", "name": "ESAt Liaison"},
    {"id": "CMP_196", "agency": "QWERTY", "name": "External Programme / Assistance"},
    {"id": "CMP_220", "agency": "QWERTY", "name": "External Programme Participation "},
    {"id": "CMP_106", "agency": "QWERTY", "name": "Foreign Pension / Entitlement Status"},
    {"id": "CMP_234", "agency": "QWERTY", "name": "Foreign Pension Reviews"},
    {"id": "CMP_259", "agency": "QWERTY", "name": "Garnishee Arrangements"},
    {"id": "CMP_001", "agency": "QWERTY", "name": "Generic Enquiry"},
    {"id": "CMP_197", "agency": "QWERTY", "name": "Generic Referral"},
    {"id": "CMP_046", "agency": "QWERTY", "name": "Homelessness Assessment"},
    {"id": "CMP_151", "agency": "QWERTY", "name": "Immediate Payment / Hardship Payment"},
    {"id": "CMP_108", "agency": "QWERTY", "name": "Immunisation / Health Check Details "},
    {"id": "CMP_235", "agency": "QWERTY", "name": "Income and Assets Review"},
    {"id": "CMP_174", "agency": "QWERTY", "name": "Income Management - Child Protection"},
    {"id": "CMP_175", "agency": "QWERTY", "name": "Income Management - Compulsory"},
    {"id": "CMP_178", "agency": "QWERTY", "name": "Income Management - Voluntary"},
    {"id": "CMP_176", "agency": "QWERTY", "name": "Income Management Compulsory - Exemptions"},
    {"id": "CMP_177", "agency": "QWERTY", "name": "Income Management -Deductions"},
    {"id": "CMP_292", "agency": "QWERTY", "name": "Income Statements"},
    {"id": "CMP_236", "agency": "QWERTY", "name": "Income Stream Reviews"},
    {"id": "CMP_111", "agency": "QWERTY", "name": "Income Streams (Super etc - Notification)"},
    {"id": "CMP_188", "agency": "QWERTY", "name": "Interim Concession Card Issue"},
    {"id": "CMP_021", "agency": "QWERTY", "name": "Interpreter Requirement"},
    {"id": "CMP_022", "agency": "QWERTY", "name": "Interview with Specialist"},
    {"id": "CMP_189", "agency": "QWERTY", "name": "Issue Basics Card "},
    {"id": "CMP_190", "agency": "QWERTY", "name": "Issue EBT Card"},
    {"id": "CMP_288", "agency": "QWERTY", "name": "Issue Information"},
    {"id": "CMP_289", "agency": "QWERTY", "name": "Issue Letter"},
    {"id": "CMP_206", "agency": "QWERTY", "name": "Job Search Efforts"},
    {"id": "CMP_207", "agency": "QWERTY", "name": "Job Search Support Only Registrations (JSSO)"},
    {"id": "CMP_208", "agency": "QWERTY", "name": "Job Seeker Classification Instrument (JSCI)"},
    {"id": "CMP_209", "agency": "QWERTY", "name": "Job Seeker Diary Issue"},
    {"id": "CMP_210", "agency": "QWERTY", "name": "Job Seeker Diary Return"},
    {"id": "CMP_113", "agency": "QWERTY", "name": "Managed Investments (Income & Assets)"},
    {"id": "CMP_114", "agency": "QWERTY", "name": "Medical Certificate"},
    {"id": "CMP_067", "agency": "QWERTY", "name": "Medical Consultation (HPAU) "},
    {"id": "CMP_260", "agency": "QWERTY", "name": "Mercantile Agent Commission"},
    {"id": "CMP_027", "agency": "QWERTY", "name": "Nominee Arrangements"},
    {"id": "CMP_282", "agency": "QWERTY", "name": "Ombudsman / Ministerial / NGO"},
    {"id": "CMP_160", "agency": "QWERTY", "name": "One Off Payment"},
    {"id": "CMP_115", "agency": "QWERTY", "name": "Other Assets (Income & Assets)"},
    {"id": "CMP_117", "agency": "QWERTY", "name": "Other Income (Income & Assets)"},
    {"id": "CMP_118", "agency": "QWERTY", "name": "Overseas Absences"},
    {"id": "CMP_211", "agency": "QWERTY", "name": "Participation Assessment (Non Serious Failure)"},
    {"id": "CMP_212", "agency": "QWERTY", "name": "Participation Assessment (Serious Failure)"},
    {"id": "CMP_213", "agency": "QWERTY", "name": "Participation Exemption "},
    {"id": "CMP_153", "agency": "QWERTY", "name": "Payday Change"},
    {"id": "CMP_154", "agency": "QWERTY", "name": "Payment Destination "},
    {"id": "CMP_155", "agency": "QWERTY", "name": "Payment Frequency / Rate"},
    {"id": "CMP_215", "agency": "QWERTY", "name": "Payment Stimulation (SU19)"},
    {"id": "CMP_290", "agency": "QWERTY", "name": "Payment Summaries"},
    {"id": "CMP_221", "agency": "QWERTY", "name": "Personal Contact Interview"},
    {"id": "CMP_240", "agency": "QWERTY", "name": "Pilot Review"},
    {"id": "CMP_028", "agency": "QWERTY", "name": "Power of Attorney"},
    {"id": "CMP_261", "agency": "QWERTY", "name": "Prosecutions"},
    {"id": "CMP_029", "agency": "QWERTY", "name": "Proof of Identification"},
    {"id": "CMP_056", "agency": "QWERTY", "name": "Qualifying Event"},
    {"id": "CMP_241", "agency": "QWERTY", "name": "Random Sample Review"},
    {"id": "CMP_120", "agency": "QWERTY", "name": "Real Estate Details"},
    {"id": "CMP_262", "agency": "QWERTY", "name": "Recovery Fee (Admin Debts)"},
    {"id": "CMP_216", "agency": "QWERTY", "name": "Reduced Work Capacity"},
    {"id": "CMP_121", "agency": "QWERTY", "name": "Relationship Status"},
    {"id": "CMP_242", "agency": "QWERTY", "name": "Rent Review"},
    {"id": "CMP_219", "agency": "QWERTY", "name": "Reporting Frequency"},
    {"id": "CMP_291", "agency": "QWERTY", "name": "Request For Further Information"},
    {"id": "CMP_131", "agency": "QWERTY", "name": "Residency"},
    {"id": "CMP_162", "agency": "QWERTY", "name": "Restoration"},
    {"id": "CMP_161", "agency": "QWERTY", "name": "Returned / Re-issue Payment"},
    {"id": "CMP_122", "agency": "QWERTY", "name": "Savings (Income & Assets)"},
    {"id": "CMP_072", "agency": "QWERTY", "name": "School Enrolment & Attendance"},
    {"id": "CMP_009", "agency": "QWERTY", "name": "Self Manage Service Access"},
    {"id": "CMP_243", "agency": "QWERTY", "name": "Service Profiling"},
    {"id": "CMP_123", "agency": "QWERTY", "name": "Shares (Income & Assets)"},
    {"id": "CMP_280", "agency": "QWERTY", "name": "Social Security Appeals Tribunal (SSAT)"},
    {"id": "CMP_156", "agency": "QWERTY", "name": "Special Employment Advance"},
    {"id": "CMP_124", "agency": "QWERTY", "name": "Study / Training Details"},
    {"id": "CMP_279", "agency": "QWERTY", "name": "Subject Matter Expert (SME)"},
    {"id": "CMP_157", "agency": "QWERTY", "name": "Suspension"},
    {"id": "CMP_158", "agency": "QWERTY", "name": "Tax Deductions"},
    {"id": "CMP_030", "agency": "QWERTY", "name": "Tax File Number"},
    {"id": "CMP_125", "agency": "QWERTY", "name": "Telephone / Internet Details"},
    {"id": "CMP_180", "agency": "QWERTY", "name": "Third Party Payment Destination"},
    {"id": "CMP_245", "agency": "QWERTY", "name": "Tip Off Review"},
    {"id": "CMP_126", "agency": "QWERTY", "name": "Trust & Companies - Notification"},
    {"id": "CMP_023", "agency": "QWERTY", "name": "Update Appointment"},
    {"id": "CMP_217", "agency": "QWERTY", "name": "Vulnerability Indicator"},
    {"id": "CMP_246", "agency": "QWERTY", "name": "Vulnerability Review"},
    {"id": "CMP_198", "agency": "QWERTY", "name": "Welfare Assistance Referral"},
    {"id": "CMP_159", "agency": "QWERTY", "name": "Withholdings"})

EXPECTED_FILENAMES = (
    'bbq_tax.json',
    'birthday_tax.json',
    'christmas_tax.json',
    'register_bbq.json',
    'space_robot_loans.json',
    'spaceship_loans.json',
    'birthday_bonus.json',
    'aditional_christmas_tax.json',
    'big_effort_bonus.json',
)

EXPECTED_AGENCY_JSONFILES = {
    'DEF': (
        'bbq_tax.json',
        'birthday_tax.json',
        'christmas_tax.json',
        'register_bbq.json',),
    'FOO': (
        'space_robot_loans.json',
        'spaceship_loans.json',),
    'QWERTY': (
        'birthday_bonus.json',),
    'XYZ': (
        'aditional_christmas_tax.json',
        'big_effort_bonus.json',),}
