# This is the crawler compose file, will need to be integrated later
FROM node:latest
COPY . /src
###VOLUME /src #
VOLUME /src/logs
VOLUME /var/mail
RUN apt-get update; apt-get -y install cron vim
WORKDIR /src
RUN npm install
RUN node testRegex.js
#Note: The following line sets up the cron job which will run wrapper.sh (and within that the crawler).
ENTRYPOINT crontab /src/crontab.txt; crontab -l; cron -f;
