postgres:
  image: postgres:latest
  env_file: postgres.env
  volumes:
    - /data:/var/lib/postgresql/data

#TODO: Get host postres to connect to this directory and create/validate database.

crawler:
  build: .
  dockerfile: crawler.dockerfile
  links:
   - postgres
  env_file: crawler.env
  restart: always
  working_dir: /src
  command: node crawl --queue 2 --time 120 --interval 2000
  #this will change to setting up cron
