FROM ubuntu:14.04
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y python-dev
RUN apt-get install -y gcc binutils
RUN apt-get install -y libxml2-dev libxslt1-dev libxml2 libxslt1-dev zlib1g-dev
RUN apt-get install -y python python-pip libpq-dev git
ENV SRC=./
ENV HOME=/opt
ENV PROJ=/opt/disco_service
RUN groupadd -r discoworker && useradd -r -g discoworker discoworker
WORKDIR $HOME
RUN mkdir media static logs
COPY $SRC $PROJ
RUN chown -R discoworker:discoworker $HOME
WORKDIR $PROJ
RUN pip install -r requirements.txt
EXPOSE 8000
COPY ./run_celery.sh /
USER discoworker
ENTRYPOINT ["/run_celery.sh"]
